sudo: false
language: go

go:
- "1.12.x"
- "1.13.x"
- "1.14.x"

# Only clone the most recent commit.
git:
  depth: 1

env:
- GOLANGCI_RELEASE="v1.4.1"

script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s ${GOLANGCI_RELEASE}
- make
# See https://github.com/asobti/kube-monkey/issues/120
# - .travis/check_workspace.sh
