{{- if .Values.rbac.enabled -}}
{{- if .Values.serviceAccount }}
{{- if not .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubemonkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end}}
{{- end}}
{{- end}}

---

{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubemonkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "kubemonkey.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
