---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 8
      start_hour = 10
      end_hour = 16
      blacklisted_namespaces = ["kube-system"]
      whitelisted_namespaces = ["chaos-test"]